# Generated by Django 4.0.4 on 2022-05-31 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 19, 12, 38, 105142)),
        ),
    ]
