# Generated by Django 4.0.4 on 2022-06-01 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 1, 6, 4, 9, 245876)),
        ),
    ]
