version: "3.1"

services:
  pgdb:
    image: postgres:12-alpine
    container_name: pgdb
    volumes:
      - pgdata:/var/lib/postgresql/data/
    # env_file:
    #   - ./.dev.env
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=django_db
    expose:
      - "5432"
    ports:
      - 5432:5432
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.dev.env
    depends_on:
      - pgdb

  frontend:
    build: ./frontend
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app
    depends_on:
      - backend

volumes:
  pgdata:
